from typing import Any, Dict, Generic, List, Type, TypeVar
from uuid import UUID
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.base_class import Base
from app.core.context import get_current_tenant_id
from app.core.exceptions import TenantIsolationError

ModelType = TypeVar("ModelType", bound=Base)


class BaseRepository(Generic[ModelType]):
    """Generic Base Repository containing standard CRUD operations with tenant scoping."""

    def __init__(self, model: Type[ModelType], db: AsyncSession):
        self.model = model
        self.db = db

    def _apply_tenant_filter(self, query):
        """Appends tenant_id criteria if the model supports tenant isolation."""
        if hasattr(self.model, "tenant_id"):
            tenant_id = get_current_tenant_id()
            if not tenant_id:
                raise TenantIsolationError("Active tenant context is required for database query filtering.")
            return query.filter(self.model.tenant_id == tenant_id)
        return query

    async def get(self, id: Any) -> ModelType | None:
        """Fetch a single record by primary key, scoped by tenant."""
        query = select(self.model).filter(self.model.id == id)
        query = self._apply_tenant_filter(query)
        result = await self.db.execute(query)
        return result.scalars().first()

    async def get_multi(self, skip: int = 0, limit: int = 100) -> List[ModelType]:
        """Fetch multiple records with offset pagination, scoped by tenant."""
        query = select(self.model).offset(skip).limit(limit)
        query = self._apply_tenant_filter(query)
        result = await self.db.execute(query)
        return list(result.scalars().all())

    async def create(self, obj_in: Dict[str, Any]) -> ModelType:
        """Create a new database record, auto-populating tenant context."""
        db_obj = self.model(**obj_in)
        
        # Enforce tenant isolation on write
        if hasattr(db_obj, "tenant_id"):
            tenant_id = get_current_tenant_id()
            if not tenant_id:
                raise TenantIsolationError("Active tenant context is required for database record insertion.")
            db_obj.tenant_id = tenant_id

        self.db.add(db_obj)
        await self.db.flush()  # Populates autogenerated fields (like id/created_at) without committing
        return db_obj

    async def update(self, db_obj: ModelType, obj_in: Dict[str, Any]) -> ModelType:
        """Update an existing database record, validating tenant ownership."""
        # Enforce tenant check on write
        if hasattr(db_obj, "tenant_id"):
            tenant_id = get_current_tenant_id()
            if db_obj.tenant_id != tenant_id:
                raise TenantIsolationError("Unauthorized modification: Record belongs to another tenant.")

        # Apply update parameters
        for field in obj_in:
            if hasattr(db_obj, field):
                setattr(db_obj, field, obj_in[field])

        self.db.add(db_obj)
        await self.db.flush()
        return db_obj

    async def remove(self, id: Any) -> ModelType | None:
        """Delete a record by primary key, scoped by tenant."""
        db_obj = await self.get(id)
        if db_obj:
            # BaseRepository.get already filters by tenant, so tenant ownership is guaranteed
            await self.db.delete(db_obj)
            await self.db.flush()
            return db_obj
        return None
